config/routes.rb
Rails.application.routes.draw do
  get "location/index", to: "location#index"
  get "search", to: "locations#search", as: :search
  get "/about", to: "about#index"
  root "champions#index"

  resources :champions
  resources :locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/champion.rb
class Champion < ApplicationRecord
  has_one :champion_stat
  belongs_to :location
  has_and_belongs_to_many :team_comps

  validates :name, presence: true, uniqueness: true
end

app/models/champion_stat.rb
class ChampionStat < ApplicationRecord
  belongs_to :champion

  validates :games_played, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :champions

  validates :name, presence: true
end

app/models/team_comp.rb
class TeamComp < ApplicationRecord
  validates :comp_name, presence: true, uniqueness: true
  has_and_belongs_to_many :champions
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  def index
    @champions = Champion.order(:name).page(params[:page]).per(10)
  end

  def show
    @champion = Champion.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.order(:name)
  end

  def show
    @location = Location.find(params[:id])
    @champions = @location.champions.order(:name)
  end

  def search
    @input = params[:query]
    @selected_location = Location.find_by(id: params[:location]) # Use find_by to avoid raising an exception if the location is not found

    if params[:query].present?
      if @selected_location.present?
        # Both query and location are present
        @champions_like = Champion.where(location_id: @selected_location.id)
                                  .where("name LIKE ?",
                                         "#{@input}%").order(:name)
                                  .page(params[:page]).per(10)
      else
        # Query is present, but no location selected
        @champions_like = Champion.where("name LIKE ?",
                                         "#{@input}%").order(:name).page(params[:page]).per(10)
      end
    else
      @champions_like = if @selected_location.present?
                          # Query is not present, but a location is selected
                          Champion.where(location_id: @selected_location.id).order(:name).page(params[:page]).per(10)
                        end
    end
  end
end

app/controllers/team_comps_controller.rb
class TeamCompsController < ApplicationController
  def index
  end

  def show
  end

  def new
    @team_comp = TeamComp.new
  end

  def create
    @team_comp = TeamComp.new(team_comp_params)
    respond_to do |format|
      if @team_comp.save
        format.html { redirect_to team_comp_url(@team_comp), notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team_comp }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team_comp.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def team_comp_params
    params.require(:team_comp).permit(:name, champion_ids: [])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def location_dropdown
    Location.order(:name).map { |location| [location.name, location.id] }
  end
end

app/helpers/champions_helper.rb
module ChampionsHelper
end

app/helpers/region_helper.rb
module RegionHelper
end

app/helpers/team_comps_helper.rb
module TeamCompsHelper
end

app/views/about/index.html.erb
<div class="container">
    <h1>About Page</h1>
    <p>For our data project we chose to use a dataset from the video game
        "League of Legends". The dataset has the playable Champions as well as
        their game stats taken from the "ARAM" game mode.</p>
    <p>We're also using "Faker" to generate the locations from the game
        using their LeagueofLegends class</p>
</div>

app/views/champions/index.html.erb
<div class="container">
    <h1>Champions</h1>

    <div class="row">
        <% @champions.each do |champion| %>
            <div class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <%= link_to champion.name, champion %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <nav>
    <div class="pagination justify-content-center">
        <%= paginate @champions %>
    </div>
    </nav>
</div>

app/views/champions/show.html.erb
<div class="container">
    <h1><%= @champion.name %></h1>
    <p>Region: <%= link_to @champion.location.name, location_path(@champion.location) %></p>
    <p>Games Played: <%= @champion.champion_stat.games_played %></p>
    <p>K/D/A: <%= @champion.champion_stat.kda %></p>
    <p>Win Rate: <%= (100 * @champion.champion_stat.win_rate).round(2) %>%</p>
    <p>Pick Rate: <%= (100 * @champion.champion_stat.pick_rate).round(2) %>%</p>
    <p>Average CS per game: <%= @champion.champion_stat.cs %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeagueOfLegends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/locations/index.html.erb
<div class="container">
    <h1>Regions</h1>
    <div class="row">
        <% @locations.each do |location| %>
            <div class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <%= link_to location.name, location %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/locations/search.html.erb
<div class="container">
  <% if @selected_location.present? %>
  <h1>Search Results for Champions in <%= @selected_location.name %></h1>

    <div class="row">
    <% if @champions_like.any? %>
      <% @champions_like.each do |champion| %>
        <div class="col-md-3">
          <div class="card mb-3">
            <div class="card-body">
              <%= link_to champion.name, champion %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <nav>
    <ul class="pagination justify-content-center">
      <%= paginate @champions_like %>
    </ul>
  </nav>
    <% else %>
      <p>No champions found in this location.</p>    <% end %>
<% else %>
  <% if @champions_like.nil?%>
    <h1>Search Results for Champions: <%= @input %> </h1>
    <p>Error: Please enter a value in the search bar or select a location from the drop down menu.</p>
  <% else %>
    <h1>Search Results for Champions: <%= @input %></h1>
    <div class="row">
      <% @champions_like.each do |champion| %>
        <div class="col-md-3">
          <div class="card mb-3">
            <div class="card-body">
              <%= link_to champion.name, champion %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  <nav>
    <div class="pagination justify-content-center">
      <%= paginate @champions_like %>
    </div>
  </nav>
  <% end %>
<% end %>
</div>

app/views/locations/show.html.erb
<div class="container">
    <h1><%= @location.name %></h1>
    <h2>Champions in this region</h2>
    <div class="row">
        <% @champions.each do |champion| %>
            <div class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <%= link_to champion.name, champion_path(champion) %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/shared/_nav.html.erb
<nav>
    <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li class="dropdown-menu">
            <%= form_tag(search_path, method: :get, class: "form-inline") do %>
                <%= text_field_tag 'query', params[:query], placeholder: 'Search Champions', class: 'form-control' %>
                <%= select_tag 'location', options_for_select(location_dropdown, params[:location]), include_blank: 'Select a Location' %>
                <%= submit_tag 'Search', class: 'btn btn-primary' %>
            <% end %>
        </li>
    </ul>
</nav>

app/views/team_comps/index.html.erb
<h1>Teams</h1>
<%= link_to "Create a Team", new_team_comp_path, class: "btn btn-primary" %>

app/views/team_comps/new.html.erb
<div class="container">
  <h1>Create a Team</h1>
  <%= form_with model: @team_comp do |f| %>
    <h2>Add Champions to Team</h2>

    <div class="row">
    <%= f.text_field :comp_name, class: "form-control", placeholder: "Team Name" %>
      <% Champion.all.sort_by(&:name).each_slice(3) do |champions_row| %>
        <div class="col-md-4">
          <% champions_row.each do |champion| %>
            <div class="form-check">
              <input type="checkbox" name="team_comp[champion_ids][]" value="<%= champion.id %>" class="form-check-input" id="champion_<%= champion.id %>">
              <label class="form-check-label" for="champion_<%= champion.id %>"><%= champion.name %></label>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= f.submit "Create Team", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/team_comps/show.html.erb
<h1>TeamComps#show</h1>
<p>Find me in app/views/team_comps/show.html.erb</p>